### ISSUE TITLE
Trains Freeze when Track Controller tells to stop

### ISSUE THREAD

**Issue by kwm19** [JKenneson/ECE1186#24]
Trains will freeze when the track controller tells them to stop. Beacons probably have something to do with this.

To Recreate: Dispatch a train and once the train is on the vertical N section, dispatch another. The train will will stop when through the track controller when the spacing is 5 blocks. Once that train has the ability to move again. It will stay at this current position with not chance to move.

**Comment by tjpro** [comment]
Fixed. Counter moved to proper place.
