### ISSUE TITLE
Update Authority Negative when above particular value

### ISSUE THREAD

**Issue by kwm19** [JKenneson/ECE1186#26]
When a train is selected from the panel on the CTC, and the option to update its speed and authority is entered. If the value for the authority is entered at 40000 or above. The authority comes out negative.

Example 40000 comes out on train controller panel as ~-25,000 ft

**Comment by kwm19** [comment]
I think this bug is in the Track Controller Handler, when `requestUpdateSpeedAuthority` is called. The number are cast as a byte and short for speed and authority respectively. We should probably alert user or explicitly set caps on the inputs.

**Comment by JKenneson** [comment]
Fixed this for the most part... The maximum authority that is allowed is around 107,000 feet.  This gets cast to meters and then is sent across as a short to the train.
